name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'
    - run: npm install
    - name: Run build
      run: npm run build
    - name: Start the application
      run: npm start &
    - name: Wait for the application to be ready
      run: npx wait-on http://localhost:3000/
    - run: npx cypress run
    - run: npm test -- --watchAll=false
